### ISSUE TITLE
The attached real-world image fails to decode

### ISSUE THREAD

**Issue by Shnatsel** [etemesi254/zune-jpeg#16]
[This 14k by 19k image](https://mega.nz/file/Ms8FTYZC#QEhDWpEaOAazQIVOpoloc32IgwMeu4dYgP9CrxMO400) fails to decode correctly in zune-jpeg. I have not inspected the output, but decoding completes in 15ms while djpeg takes well over a second, which sounds too good to be true.

This is an AI upscale of the image used in #15 - same content, different resolution. Don't mix them up!

**Comment by etemesi254** [comment]
This fails because of a warning

-Too large dimensions.

It's a library limit because most corrupt images try to set that up as a high value which makes the library pre-allocate a huge array, so I decided to cap that limit to a reasonable number.

I.e this particular image would allocate  278,451,008 bytes -> 256 MB which is quite huge for an image.

I can relax requirements, but someone somewhere may have an out of memory exception.

**Comment by Shnatsel** [comment]
Ah! That's a very reasonable protection. 

However, there are lots of different requirements that people may have with regard to these limits - for example, a desktop image viewer may set them very high or remove them entirely, while a server handling e.g. Github avatars will want to set them quite low.

This is why most mature decoders let the user configure the limits. See e.g. the [`Limits`](https://docs.rs/image/0.24.3/image/io/struct.Limits.html) struct in the `image` crate.

**Comment by Shnatsel** [comment]
Also, I'd argue that 256Mb is not a lot by modern standards - even a $35 Raspberry Pi has gigabytes of RAM. But I don't care about the defaults all that much as long as the limits are configurable.

**Comment by etemesi254** [comment]
Configurable as in allowing the user to set  limits via functions?

**Comment by etemesi254** [comment]
*Sorry missed that first comment.

`configure_limits(width, height)` as an api sounds usable,

**Comment by Shnatsel** [comment]
I think `set_limits()` is more concise, [like in `image`](https://docs.rs/image/0.24.3/image/trait.ImageDecoder.html#method.set_limits), but I don't have a strong opinion about that.

**Comment by etemesi254** [comment]
Addressed in https://github.com/etemesi254/zune-jpeg/commit/d610f00dfcc360459ebe556db8768bb0901d5697

(A bit noisy, due to rustfmt)

To protect most people who would ignore it and have large allocations 
I've set the defaults to be 16,384 by 16,384, which means this image won't decode

but with this modified code 
```rust
use zune_jpeg::Decoder;
use std::fs::File;
use std::io::BufReader;

fn main() -> std::io::Result<()> {
    let path = std::env::args().skip(1).next().unwrap();
    let mut decoder = Decoder::new();

    // new api !!!
    decoder.set_limits(u16::MAX,u16::MAX);

    decoder.decode_file(path);
    Ok(())
}
```
It should decode
