### ISSUE TITLE
How do I find the stride of an image?

### ISSUE THREAD

**Issue by asnimansari** [etemesi254/zune-jpeg#26]

**Comment by etemesi254** [comment]
Hi, I'm assuming the stride is separation of one row to another,

Then that becomes the width.

After decoding an image, you can access it's width by using `width()` method

**Comment by asnimansari** [comment]
Thanks for the update.

**Comment by asnimansari** [comment]
Not sure if it is same as width when padding is present

**Comment by etemesi254** [comment]
Hi
Just wondering why would you need that?


Currently not exposed since it may vary per component.

Some jpeg images do what we call chroma subsampling or downsampling


So take for example hv sampling or 4:2:0 sampling.

An image with a width of 1080 will have the following width strides

Y component: 1080
Cb component:540
Cr component: 540
(JPEG internally converts RGB to ul YCbCr component)

This means we can't expose those values because they probably wont do what
you want them to do at all.
