### ISSUE TITLE
`align_alloc` is unsound

### ISSUE THREAD

**Issue by HeroicKatora** [etemesi254/zune-jpeg#4]
Referring to:

https://github.com/etemesi254/zune-jpeg/blob/27c2c389a376592402cdecfdc3bcc9106208c708/src/unsafe_utils.rs#L183-L199

Quoting [Vec::from_raw_parts](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.from_raw_parts), emphasis by me:

> T needs to have the same size and alignment as what ptr was allocated with. (T **having a less strict alignment is not sufficient**, the alignment really needs to be equal to satisfy the [dealloc](https://doc.rust-lang.org/stable/std/alloc/trait.GlobalAlloc.html#tymethod.dealloc) requirement that memory must be allocated and deallocated with the same layout.)

This is exactly what the code is doing here.

**Comment by etemesi254** [comment]
Yes, forgot to mention it though.

All blocks called by `align_alloc` **should not resize**.(I keep that as an invariant within my code).

It's used in three places actually( only one of them important, I'm supposed to remove it).


1. https://github.com/etemesi254/zune-jpeg/blob/c72764bd8d743d4714201a5b9aeab6475567b2f4/src/idct/avx2.rs#L69

2. https://github.com/etemesi254/zune-jpeg/blob/c72764bd8d743d4714201a5b9aeab6475567b2f4/src/upsampler/avx2.rs#L52

3. https://github.com/etemesi254/zune-jpeg/blob/c72764bd8d743d4714201a5b9aeab6475567b2f4/src/upsampler/sse.rs#L31


All of them don't reallocate, at all, so the library kind of pinky swears that invariant is upheld.

The intent was to get sse/avx aligned memory blocks, so that we can use the `_mm/_mm256_store` and load instructions which are sometimes faster than their unaligned loads (`_mm/_mm256_loadu_`)(Loads crossing cache lines are 1 cycle more see https://travisdowns.github.io/blog/2019/06/11/speed-limits.html#load-split-cache-lines.   I admit I was a bit paranoid at that point). 

But I am to remove it and still appreciate you pointing that out.

Your solution is a quite something actually,(never thought of that), but I do have one question? How much bytes are wasted if I want a Texel of u8's whose size is 17 bytes?And what if I want to combine the 15'th,16'th , 17'th and 18th u8s into a u32, how do I express that?

**Comment by HeroicKatora** [comment]
> All blocks called by align_alloc should not resize.(I keep that as an invariant within my code).

Also it *must not be dropped* as a `Vec<_>`. Technically, it's already unsound at the call site of `from_raw_parts`. (I'm wondering though, if no resizing is intended, then you might allocate a `Box<[…]>` instead and safe a `usize` being moved around constantly on the stack.) I have a hard time following the pinky swear. The samples allocated in such a way escape [at least until here](https://github.com/etemesi254/zune-jpeg/blob/c72764bd8d743d4714201a5b9aeab6475567b2f4/src/worker.rs#L118) and that's so far from the original call-site, it's almost impossible to uphold the property in all future versions. Someone's bound to make a change that returns that vector to the user at some point and expose the UB.

> Your solution is a quite something actually,(never thought of that), but I do have one question? How much bytes are wasted if I want a Texel of u8's whose size is 17 bytes?

A total of 15 bytes, it rounds up to the full type. That's mostly because the solution intends to reuse as much of the (safe) vector interface as possible. Since most of that is not required here, in your case, it might actually be best to write a custom constainer (or Box) to manage the allocation then. That shouldn't be a lot harder than what's already there, there is no magic inside of `Vec<_>` in terms of operations.

> And what if I want to combine the 15'th,16'th , 17'th and 18th u8s into a u32, how do I express that?

Not so simply becase that's an unaligned load to begin with. However, a good try might be:

```
// Trust that the unwrap is removed by llvm.
let bytes: &[u8; 4] = buffer.as_bytes()[15..19].try_into().unwrap();
let val: u32 = u32::from_ne_bytes(*bytes);
```

**Comment by etemesi254** [comment]
That makes sense, will  remove it.

And also, how would you implement C's [aligned_alloc](https://en.cppreference.com/w/c/memory/aligned_alloc), with your experience in Rust?(Or anyone for that matter).

And isn't `Texels<T>` a lot of` [u8;16]` blocks, doesn't that mean that accessing byte 16 and 17 requires something like

```rust

let texel  = vec![[0;16],20];
// Combine two bytes into a u16
let combined = ((u16::from(texel[0][15]))<<8) | u16::from(texel[1][0]) 
```

**Comment by HeroicKatora** [comment]
The allocation bit is good. You just need to ensure it's paired with a call to [`dealloc`](https://doc.rust-lang.org/stable/std/alloc/fn.dealloc.html) with the *same* layout (exactly the same). That's probably the only difference to C in the allocator interface–Rust requires you to pass the correct layout to both ends.

Regardin access, Rust doesn't have type-based-alias-analysis. It's sound to access `[[u8; 16]]` that as a single, longer byteslice. The unsound portion lies only with the vector type. Thus, the library reinterprets the slice as a byte slice and accesses the memory byte offsets directly. Reading `[u8; 4]` doesn't come with any alignment obligations, then the conversion happens on the value. LLVM removes that intermediate variable immediately. Your code sketch would compile to similar code though.

**Comment by etemesi254** [comment]
The code produces branches if the vectors/slice's size is unknown, see https://godbolt.org/z/3dTEYjoTW since Rust must ensure the access is in bounds.Depending on the surrounding code, that may be costly.

But I wholly agree with your assessment, will fix in the next 1-2 days as I also try to improve the Huffman decoder.
